name: vcr_http
description: Store and mock requests made with the http package
version: 0.0.1
homepage: https://github.com/rorystephenson/vcr_http

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ">=0.12.0 <1.0.0"
  yaml: ">=2.2.0 <3.0.0"
  path: ">=1.7.0 <2.0.0"

dev_dependencies:
  test: '<2.0.0'
